In [13]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [14]:
df = pd.read_excel("Iris.xlsx",index_col = None)

In [15]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [16]:
np.random.seed(1234)
X = df[df.columns[:-1]]
Y = df["class"]
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3)

## Arbol de Desicion

In [17]:
from sklearn.tree import DecisionTreeClassifier, plot_tree

In [18]:
import sklearn
sklearn.__version__

'0.19.2'

In [27]:
arbol = DecisionTreeClassifier()

In [28]:
arbol.fit(X_train,y_train)
y_pred = arbol.predict(X_test)

In [29]:
accuracy_score(y_test,y_pred)

0.9777777777777777

In [30]:
confusion_matrix(y_test,y_pred)

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 12]], dtype=int64)

In [32]:
# Crear una lista de valores de clase
lista_clases = df["class"].unique()

In [39]:
lista_clases

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [42]:
# crear grafica de arbol
import graphviz
from sklearn.tree import export_graphviz

ModuleNotFoundError: No module named 'graphviz'

In [41]:
export_graphviz(arbol, out_file="Arbol.dot",feature_names=df.columns[:-1],class_names=lista_clases,filled=True)

NameError: name 'export_graphviz' is not defined

In [43]:
import pydot

plt.

ModuleNotFoundError: No module named 'pydot'

# Bagging

In [58]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC

In [65]:
df["class"] = df["class"].astype("category")
df["class_code"]=df["class"].cat.codes
df.head()

sepal_length  sepal_width  petal_length  petal_width        class  \
0           5.1          3.5           1.4          0.2  Iris-setosa   
1           4.9          3.0           1.4          0.2  Iris-setosa   
2           4.7          3.2           1.3          0.2  Iris-setosa   
3           4.6          3.1           1.5          0.2  Iris-setosa   
4           5.0          3.6           1.4          0.2  Iris-setosa   

   class_code  
0           0  
1           0  
2           0  
3           0  
4           0

In [62]:
Y = df["class_code"]


In [67]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3)
bag = BaggingClassifier(base_estimator=SVC())
bag.fit(X_train,y_train)

BaggingClassifier(base_estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [48]:
y__pred3 = bag.predict(X_test)


In [49]:
accuracy_score(y_test,y__pred3)

0.9555555555555556

In [50]:
confusion_matrix(y_test,y__pred3)

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  1, 11]], dtype=int64)

# Forest

In [55]:
##
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier()
forest.fit(X_train,y_train)
y_pred2 = forest.predict(X_test)
accuracy_score(y_test,y_pred2)
confusion_matrix(y_test,y_pred2)

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  1, 11]], dtype=int64)