# Métricas para clasificación (II)
## Problema multiclase

In [1]:
# Cargar las librerías
import pandas as pd
import numpy as np

In [3]:
# Cargar el dataset Iris
df = pd.read_excel("Iris.xlsx")

In [4]:
# Mostrar los 5 primeros registros
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
# Dividir el dataset entre entrenamiento y prueba
from sklearn.model_selection import train_test_split
np.random.seed(1234)
X = df[df.columns[:-1]]
Y = df["class"]
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3)

# Modelos Bagging con Máquinas de Soporte Vectorial

In [8]:
# Importar librerías
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC

## Kernel de base radial (Gaussiano)

In [11]:
# Instanciar el modelo y entrenarlo
# por defecto trae la base radial, no es necesario parametro
model_bag1 = BaggingClassifier(base_estimator=SVC())
model_bag1.fit(X_train,y_train)

BaggingClassifier(base_estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                     class_weight=None, coef0=0.0,
                                     decision_function_shape='ovr', degree=3,
                                     gamma='scale', kernel='rbf', max_iter=-1,
                                     probability=False, random_state=None,
                                     shrinking=True, tol=0.001, verbose=False),
                  bootstrap=True, bootstrap_features=False, max_features=1.0,
                  max_samples=1.0, n_estimators=10, n_jobs=None,
                  oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [12]:
# Predecir para la partición de prueba
y_pred1 = model_bag1.predict(X_test)

## Kernel  polinómico

In [13]:
# Instanciar el modelo y entrenarlo
model_bag2 = BaggingClassifier(base_estimator=SVC(kernel="poly"))
model_bag2.fit(X_train,y_train)

BaggingClassifier(base_estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                     class_weight=None, coef0=0.0,
                                     decision_function_shape='ovr', degree=3,
                                     gamma='scale', kernel='poly', max_iter=-1,
                                     probability=False, random_state=None,
                                     shrinking=True, tol=0.001, verbose=False),
                  bootstrap=True, bootstrap_features=False, max_features=1.0,
                  max_samples=1.0, n_estimators=10, n_jobs=None,
                  oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [26]:
# Predecir para la partición de prueba
y_pred2= model_bag2.predict(X_test)

## Kernel  sigmoidal

In [21]:
# Instanciar el modelo y entrenarlo
model_bag3 = BaggingClassifier(base_estimator=SVC(kernel="sigmoid"))
model_bag3.fit(X_train,y_train)

BaggingClassifier(base_estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                     class_weight=None, coef0=0.0,
                                     decision_function_shape='ovr', degree=3,
                                     gamma='scale', kernel='sigmoid',
                                     max_iter=-1, probability=False,
                                     random_state=None, shrinking=True,
                                     tol=0.001, verbose=False),
                  bootstrap=True, bootstrap_features=False, max_features=1.0,
                  max_samples=1.0, n_estimators=10, n_jobs=None,
                  oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [20]:
# Predecir para la partición de prueba
y_pred3= model_bag3.predict(X_test)

# Comparación de métricas

In [42]:
# Importar librerías 
from sklearn.metrics import accuracy_score,balanced_accuracy_score,confusion_matrix,precision_score
from sklearn.metrics import f1_score,classification_report, recall_score

La exactitud para clasificación multiclase se calcula igual que para clasificación binaria

In [27]:
# Exactitud ACC de cada modelo
ACC1 = accuracy_score(y_test,y_pred1)
ACC2 = accuracy_score(y_test,y_pred2)
ACC3 = accuracy_score(y_test,y_pred3)

print("Kernel base radial",ACC1,ACC2,ACC3)

Kernel base radial 0.9777777777777777 1.0 0.35555555555555557


La exactitud balanceada hace un promedio ponderado, si el clasficador se desempeña igual de bien en todas las clases, el indicador será similar que la exactitud normal. Si el parámetro *adjusted* es True, el BAC tomará valores entre $\frac{1}{n}$ y 1, siendo $n$ el número de clases incluso si se realiza una clasificación aleatoria. Si el parámtreo es False el BAC tomará valores entre 0 y 1.

In [30]:
# Exactitud balanceada BAC de cada modelo
BAC1 = balanced_accuracy_score(y_test,y_pred1)
BAC2 = balanced_accuracy_score(y_test,y_pred2)
BAC3 = balanced_accuracy_score(y_test,y_pred3)

print('Kernel base radial {} Kernel polinomico {} Kernel sigmoidal {}'.format(BAC1,BAC2,BAC3))

Kernel base radial 0.9803921568627452 Kernel polinomico 1.0 Kernel sigmoidal 0.3333333333333333


La precisión para el caso multiclase tiene varias formas de calcularse, dependiendo el valor que se le de al parámetro *average*: 
* 'micro': calcula la precisión global haciendo que sea igual a la exactitud. 
* 'macro': calcula la precisión para cada clase y las promedia.
* 'weighted': calcula la precisión para cada clase y las promedia en forma ponderada con base en el soporte (número de instancias por clase.

In [38]:
# Precición (sin ponderar) para cada modelo
PPV1 = precision_score(y_test,y_pred1,average="macro")
PPV2 = precision_score(y_test,y_pred2,average="macro")
## zero_division cambia una division por cero a 1
PPV3 = precision_score(y_test,y_pred3,average="macro",zero_division=1)
print('Kernel base radial {} Kernel polinomico {} Kernel sigmoidal {}'.format(PPV1,PPV2,PPV3))

Kernel base radial 0.9743589743589745 Kernel polinomico 1.0 Kernel sigmoidal 0.7851851851851852


In [39]:
# Precición ponderada para cada modelo
PPV1_P = precision_score(y_test,y_pred1,average="weighted")
PPV2_P = precision_score(y_test,y_pred2,average="weighted")
## zero_division cambia una division por cero a 1
PPV3_P = precision_score(y_test,y_pred3,average="weighted",zero_division=1)
print('Kernel base radial {} Kernel polinomico {} Kernel sigmoidal {}'.format(PPV1_P,PPV2_P,PPV3_P))

Kernel base radial 0.9743589743589745 Kernel polinomico 1.0 Kernel sigmoidal 0.7851851851851852


La sensibilidad o tasa de verdaderos positivos para el caso multiclase tiene varias formas de calcularse, dependiendo el valor que se le de al parámetro *average*: 
* 'micro': calcula la sensibilidad global. 
* 'macro': calcula la sensibilidad para cada clase y las promedia.
* 'weighted': calcula la sensibilidad para cada clase y las promedia en forma ponderada con base en el soporte (número de instancias por clase.

In [46]:
# Sensibilidad (sin ponderar) para cada modelo
VPR1= recall_score(y_test,y_pred1,average='macro')
VPR2= recall_score(y_test,y_pred2,average='macro')
VPR3= recall_score(y_test,y_pred3,average='macro')

print('Kernel base radial {} Kernel polinomico {} Kernel sigmoidal {}'.format(VPR1,VPR2,VPR3))

Kernel base radial 0.9803921568627452 Kernel polinomico 1.0 Kernel sigmoidal 0.3333333333333333


In [48]:
# Sensibilidad ponderada para cada modelo
VPR1_P= recall_score(y_test,y_pred1,average='weighted')
VPR2_P= recall_score(y_test,y_pred2,average='weighted')
VPR3_P= recall_score(y_test,y_pred3,average='weighted')

print('Kernel base radial {} Kernel polinomico {} Kernel sigmoidal {}'.format(VPR1_P,VPR2_P,VPR3_P))

Kernel base radial 0.9777777777777777 Kernel polinomico 1.0 Kernel sigmoidal 0.35555555555555557


F1 calculado como:
$$F1= 2 * \frac{PPV + VPR}{PPV * VPR}$$

Interpretado como el promedio ponderado de la precisión y sensibilidad. El mejor valor es 1, el peor es 0.

El F1 para el caso multiclase tiene varias formas de calcularse, dependiendo el valor que se le de al parámetro *average*: 
* 'micro': calcula el F1 global. 
* 'macro': calcula el F1 para cada clase y los promedia.
* 'weighted': calcula el F1 para cada clase y los promedia en forma ponderada con base en el soporte (número de instancias por clase.

In [51]:
# F1 (sin ponderar) para cada modelo
F1_1 = f1_score(y_test,y_pred1,average='macro')
F1_2 = f1_score(y_test,y_pred2,average='macro')
F1_3 = f1_score(y_test,y_pred3,average='macro')
print('Kernel base radial {} Kernel polinomico {} Kernel sigmoidal {}'.format(F1_1,F1_2,F1_3))

Kernel base radial 0.9765656565656565 Kernel polinomico 1.0 Kernel sigmoidal 0.17486338797814208


In [52]:
# F1 ponderado para cada modelo
F1_1_P = f1_score(y_test,y_pred1,average='weighted')
F1_2_P = f1_score(y_test,y_pred2,average='weighted')
F1_3_P = f1_score(y_test,y_pred3,average='weighted')
print('Kernel base radial {} Kernel polinomico {} Kernel sigmoidal {}'.format(F1_1_P,F1_2_P,F1_3_P))

Kernel base radial 0.9778855218855219 Kernel polinomico 1.0 Kernel sigmoidal 0.18652094717668488


Reporte resumen de métricas

In [54]:
# Crear listas con nombre de clases
nombre_clases = df['class'].unique()

# Modelo 1: Bagging de modelos SVM con kernel de base radial
print(classification_report(y_test,y_pred1,target_names=nombre_clases))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.94      0.97        17
 Iris-virginica       0.92      1.00      0.96        12

       accuracy                           0.98        45
      macro avg       0.97      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45



In [55]:
# Modelo 2: Bagging de modelos SVM con kernel de polinómico
print(classification_report(y_test,y_pred2,target_names=nombre_clases))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      1.00      1.00        17
 Iris-virginica       1.00      1.00      1.00        12

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



In [56]:
# Modelo 3: Bagging de modelos SVM con kernel sigmoidal
print(classification_report(y_test,y_pred3,target_names=nombre_clases,zero_division=1))

                 precision    recall  f1-score   support

    Iris-setosa       0.36      1.00      0.52        16
Iris-versicolor       1.00      0.00      0.00        17
 Iris-virginica       1.00      0.00      0.00        12

       accuracy                           0.36        45
      macro avg       0.79      0.33      0.17        45
   weighted avg       0.77      0.36      0.19        45



In [57]:
# En el caso anterior es necesario eliminar la división por cero ya que hay clases que no se clasifican correctamente nunca
# Se imprime la matriz de confusión del modelo 3
confusion_matrix(y_test,y_pred3)

array([[16,  0,  0],
       [17,  0,  0],
       [12,  0,  0]], dtype=int64)

In [58]:
#se imprime la matriz de confusion del modelo 2
confusion_matrix(y_test,y_pred2)

array([[16,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 12]], dtype=int64)

In [59]:
#se imprime la matriz de confusion del modelo 1
confusion_matrix(y_test,y_pred1)

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 12]], dtype=int64)

In [62]:
# calcular predicciones con el modelo 2 (polinomial) sobre la particion de entrenamiento
# verificar sobreajuste, si estuviera sobreajustado 2 datos darias 1 por ejemplo
y_pred_train=model_bag2.predict(X_train)
confusion_matrix(y_pred_train,y_train)

array([[34,  0,  0],
       [ 0, 30,  0],
       [ 0,  3, 38]], dtype=int64)